/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delivery.vista;

/**
 *
 * @author badle
 */
public class FrmCliente extends javax.swing.JInternalFrame {


    /**
     * Creates new form FrmClientes
     */
    public FrmCliente() {
        initComponents();
        validarClientes();
    }
    public void validarClientes() {
        if (jTxNombre.getText().isEmpty()) {
            jlbNombre1.setText("*Campo Requerido");

        } else if (jTxNombre.getText().length() > 30) {
            jlbNombre1.setText("*Máximo 30 caracteres");

        } else {
            jlbNombre1.setText("");
        }

        if (jTxCedula.getText().isEmpty()) {
            jlbCedula1.setText("*Campo Requerido");

        } else if (jTxCedula.getText().length() > 10) {
            jlbCedula1.setText("*Máximo 10 caracteres");

        } else {
            jlbCedula1.setText("");
        }
        if (jTxApellidos.getText().isEmpty()) {
           jlbApellidos1.setText("*Campo Requerido");

        } else if (jTxApellidos.getText().length() > 30) {
           jlbApellidos1.setText("*Máximo 30 caracteres");

        } else {
           jlbApellidos1.setText("");
        }
        if (jTxTelefono.getText().isEmpty()) {
           jlbTelefono1.setText("*Campo Requerido");

        } else if (jTxTelefono.getText().length() > 10) {
           jlbTelefono1.setText("*Máximo 10 caracteres");

        } else {
           jlbTelefono1.setText("");
        }
        if (jTxCelular.getText().isEmpty()) {
           jlbCelular1.setText("*Campo Requerido");

        } else if (jTxCelular.getText().length() > 10) {
           jlbCelular1.setText("*Máximo 10 caracteres");

        } else {
           jlbCelular1.setText("");
        }
        if (jTxEdad.getText().isEmpty()) {
           jlbEdad1.setText("*Campo Requerido");

        } else if (jTxEdad.getText().length() > 20) {
           jlbEdad1.setText("*Máximo 20 caracteres");

        } else {
           jlbEdad1.setText("");
        }
        if (jTxDireccion.getText().isEmpty()) {
           jlbDireccion1.setText("*Campo Requerido");

        } else if (jTxDireccion.getText().length() > 40) {
           jlbDireccion1.setText("*Máximo 40 caracteres");

        } else {
           jlbDireccion1.setText("");
        }
        if (jTxCiudad.getText().isEmpty()) {
           jlbCiudad1.setText("*Campo Requerido");

        } else if (jTxCiudad.getText().length() > 11) {
           jlbCiudad1.setText("*Máximo 11 caracteres");

        } else {
           jlbCiudad1.setText("");
        }
        
        if (jTxBarrio.getText().isEmpty()) {
           jlbBarrio1.setText("*Campo Requerido");

        } else if (jTxBarrio.getText().length() > 20) {
           jlbBarrio1.setText("*Máximo 20 caracteres");

        } else {
           jlbBarrio1.setText("");
        }

        if (jTxCorreoElectronico.getText().isEmpty()) {
            jlbEmail1.setText("*Campo Requerido");

        } else if (jTxCorreoElectronico.getText().length() > 30) {
            jlbEmail1.setText("*Máximo 30 caracteres");

        } else {
            jlbEmail1.setText("");
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxNombre = new javax.swing.JTextField();
        jTxCedula = new javax.swing.JTextField();
        jTxTelefono = new javax.swing.JTextField();
        jTxCelular = new javax.swing.JTextField();
        jTxDireccion = new javax.swing.JTextField();
        jTxEdad = new javax.swing.JTextField();
        jTxCiudad = new javax.swing.JTextField();
        jTxApellidos = new javax.swing.JTextField();
        JBtGuardar = new javax.swing.JButton();
        JBtNuevo = new javax.swing.JButton();
        JBtEliminar = new javax.swing.JButton();
        JBtModificar = new javax.swing.JButton();
        JBtConsultar = new javax.swing.JButton();
        JBtSalir = new javax.swing.JButton();
        jlbApellidos1 = new javax.swing.JLabel();
        jlbCedula = new javax.swing.JLabel();
        jlbCelular = new javax.swing.JLabel();
        jlbApellidos = new javax.swing.JLabel();
        jlbTelefono = new javax.swing.JLabel();
        jlbDireccion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxBarrio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxCorreoElectronico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jlbNombre1 = new javax.swing.JLabel();
        jlbCedula1 = new javax.swing.JLabel();
        jlbTelefono1 = new javax.swing.JLabel();
        jlbEdad1 = new javax.swing.JLabel();
        jlbBarrio1 = new javax.swing.JLabel();
        jlbCiudad1 = new javax.swing.JLabel();
        jlbEmail1 = new javax.swing.JLabel();
        jlbCelular1 = new javax.swing.JLabel();
        jlbDireccion1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setMaximizable(true);
        setTitle("Registro Cliente");
        setPreferredSize(new java.awt.Dimension(698, 396));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cédula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel7.setText("Edad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 14, -1, 10));

        jLabel5.setText("Celular");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel10.setText("Correo Electronico");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 100, 40));

        jTxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxNombreActionPerformed(evt);
            }
        });
        jTxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxNombreKeyReleased(evt);
            }
        });
        getContentPane().add(jTxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 11, 270, -1));

        jTxCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxCedulaKeyReleased(evt);
            }
        });
        getContentPane().add(jTxCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 270, -1));

        jTxTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxTelefonoKeyReleased(evt);
            }
        });
        getContentPane().add(jTxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 297, -1));

        jTxCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxCelularKeyReleased(evt);
            }
        });
        getContentPane().add(jTxCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 270, 20));

        jTxDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxDireccionKeyReleased(evt);
            }
        });
        getContentPane().add(jTxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 299, -1));

        jTxEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxEdadActionPerformed(evt);
            }
        });
        jTxEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxEdadKeyReleased(evt);
            }
        });
        getContentPane().add(jTxEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 270, -1));

        jTxCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxCiudadKeyReleased(evt);
            }
        });
        getContentPane().add(jTxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 300, -1));

        jTxApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxApellidosKeyReleased(evt);
            }
        });
        getContentPane().add(jTxApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 296, -1));

        JBtGuardar.setText("GUARDAR");
        JBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(JBtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 93, -1));

        JBtNuevo.setText("NUEVO");
        getContentPane().add(JBtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 89, -1));

        JBtEliminar.setText("ELIMINAR");
        getContentPane().add(JBtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 93, -1));

        JBtModificar.setText("MODIFICAR");
        JBtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtModificarActionPerformed(evt);
            }
        });
        getContentPane().add(JBtModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        JBtConsultar.setText("CONSULTAR");
        JBtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(JBtConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        JBtSalir.setText("SALIR");
        JBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtSalirActionPerformed(evt);
            }
        });
        getContentPane().add(JBtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 93, -1));
        getContentPane().add(jlbApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 260, 20));
        getContentPane().add(jlbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 83, 273, -1));
        getContentPane().add(jlbCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 125, 273, -1));
        getContentPane().add(jlbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 43, 296, -1));
        getContentPane().add(jlbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 83, 297, -1));
        getContentPane().add(jlbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 125, 297, -1));

        jLabel8.setText("Barrio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 38, -1));

        jTxBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxBarrioActionPerformed(evt);
            }
        });
        jTxBarrio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxBarrioKeyReleased(evt);
            }
        });
        getContentPane().add(jTxBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 270, -1));

        jLabel9.setText("Ciudad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jTxCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxCorreoElectronicoKeyReleased(evt);
            }
        });
        getContentPane().add(jTxCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 280, -1));

        jLabel6.setText("Direccion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));
        getContentPane().add(jlbNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 260, 20));
        getContentPane().add(jlbCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 260, 20));
        getContentPane().add(jlbTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 290, 20));
        getContentPane().add(jlbEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 270, 20));
        getContentPane().add(jlbBarrio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 270, 20));
        getContentPane().add(jlbCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 300, 20));
        getContentPane().add(jlbEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 280, 20));
        getContentPane().add(jlbCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 270, 20));
        getContentPane().add(jlbDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 300, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtGuardarActionPerformed
        validarClientes();
    }//GEN-LAST:event_JBtGuardarActionPerformed

    private void JBtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtModificarActionPerformed

    private void jTxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxNombreActionPerformed
        validarClientes();
    }//GEN-LAST:event_jTxNombreActionPerformed

    private void JBtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtConsultarActionPerformed

    private void JBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtSalirActionPerformed
  
    }//GEN-LAST:event_JBtSalirActionPerformed

    private void jTxNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxNombreKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxNombreKeyReleased

    private void jTxCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxCedulaKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxCedulaKeyReleased

    private void jTxCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxCelularKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxCelularKeyReleased

    private void jTxDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxDireccionKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxDireccionKeyReleased

    private void jTxApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxApellidosKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxApellidosKeyReleased

    private void jTxTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxTelefonoKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxTelefonoKeyReleased

    private void jTxEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxEdadKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxEdadKeyReleased

    private void jTxCiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxCiudadKeyReleased
        validarClientes();
    }//GEN-LAST:event_jTxCiudadKeyReleased

    private void jTxEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxEdadActionPerformed

    private void jTxBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxBarrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxBarrioActionPerformed

    private void jTxBarrioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxBarrioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxBarrioKeyReleased

    private void jTxCorreoElectronicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxCorreoElectronicoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxCorreoElectronicoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBtConsultar;
    public javax.swing.JButton JBtEliminar;
    public javax.swing.JButton JBtGuardar;
    public javax.swing.JButton JBtModificar;
    public javax.swing.JButton JBtNuevo;
    public javax.swing.JButton JBtSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTxApellidos;
    public javax.swing.JTextField jTxBarrio;
    public javax.swing.JTextField jTxCedula;
    public javax.swing.JTextField jTxCelular;
    public javax.swing.JTextField jTxCiudad;
    public javax.swing.JTextField jTxCorreoElectronico;
    public javax.swing.JTextField jTxDireccion;
    public javax.swing.JTextField jTxEdad;
    public javax.swing.JTextField jTxNombre;
    public javax.swing.JTextField jTxTelefono;
    private javax.swing.JLabel jlbApellidos;
    private javax.swing.JLabel jlbApellidos1;
    private javax.swing.JLabel jlbBarrio1;
    private javax.swing.JLabel jlbCedula;
    private javax.swing.JLabel jlbCedula1;
    private javax.swing.JLabel jlbCelular;
    private javax.swing.JLabel jlbCelular1;
    private javax.swing.JLabel jlbCiudad1;
    private javax.swing.JLabel jlbDireccion;
    private javax.swing.JLabel jlbDireccion1;
    private javax.swing.JLabel jlbEdad1;
    private javax.swing.JLabel jlbEmail1;
    private javax.swing.JLabel jlbNombre1;
    private javax.swing.JLabel jlbTelefono;
    private javax.swing.JLabel jlbTelefono1;
    // End of variables declaration//GEN-END:variables

   
    }

    

