/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delivery.vista;

/**
 *
 * @author Hogar
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public FrmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtnuevo = new javax.swing.JButton();
        jTxidusuario = new javax.swing.JTextField();
        jBtsalir = new javax.swing.JButton();
        jBtconsultar = new javax.swing.JButton();
        jBteliminar = new javax.swing.JButton();
        jBtmodificar = new javax.swing.JButton();
        jBtguardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxusuario = new javax.swing.JTextField();
        jTxnombre = new javax.swing.JTextField();
        jTxcorreo = new javax.swing.JTextField();
        jPscontraseña = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 204, 204));
        setTitle("Usuarios");

        jLabel1.setText("idusuario");

        jBtnuevo.setText("Nuevo");

        jTxidusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxidusuarioActionPerformed(evt);
            }
        });

        jBtsalir.setText("Salir");
        jBtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtsalirActionPerformed(evt);
            }
        });

        jBtconsultar.setText("Consultar");

        jBteliminar.setText("Eliminar");

        jBtmodificar.setText("Modificar");

        jBtguardar.setText("Guardar");

        jLabel2.setText("nombre Usuario");

        jLabel3.setText("usuario");

        jLabel4.setText("contraseña");

        jLabel5.setText("correoE");

        jTxusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxusuarioActionPerformed(evt);
            }
        });

        jTxnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxnombreActionPerformed(evt);
            }
        });

        jTxcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxcorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTxidusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTxusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTxcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jPscontraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jBtguardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtconsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBteliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtsalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPscontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnuevo)
                    .addComponent(jBtconsultar)
                    .addComponent(jBteliminar)
                    .addComponent(jBtmodificar)
                    .addComponent(jBtguardar)
                    .addComponent(jBtsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxidusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxidusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxidusuarioActionPerformed

    private void jTxusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxusuarioActionPerformed

    private void jTxnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxnombreActionPerformed

    private void jTxcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxcorreoActionPerformed

    private void jBtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtconsultar;
    public javax.swing.JButton jBteliminar;
    public javax.swing.JButton jBtguardar;
    public javax.swing.JButton jBtmodificar;
    public javax.swing.JButton jBtnuevo;
    public javax.swing.JButton jBtsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPscontraseña;
    public javax.swing.JTextField jTxcorreo;
    public javax.swing.JTextField jTxidusuario;
    public javax.swing.JTextField jTxnombre;
    public javax.swing.JTextField jTxusuario;
    // End of variables declaration//GEN-END:variables

    public void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
